/*
 * Juego Desarrollado por Natalia Ximena Buitrago Escobar
 * Para la materia Programación Orientada a Objetos de la Corporación Minuto de Dios
 * Mayo 2023
 */

import javax.swing.ImageIcon;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;

public class InterfazGrafica extends javax.swing.JFrame {
    
    int CPU_manoEleccion = 0;
    int contadorTiempo = 0;
    int contadorPuntaje = 0; 
    
    Random random = new Random();
    Timer temporizador;
    TimerTask usoTemporizador;

    public InterfazGrafica() {
        initComponents();
        
        Estado_Tag.setVisible(false);
        
        JugadorRoll.setVisible(false);
        CPU_Roll.setVisible(false);
        
        Boton_Piedra.setVisible(false);
        Boton_Papel.setVisible(false);
        Boton_Tijera.setVisible(false);
        
        Jugador_Puntaje.setText("0");
    }
    
    //----------------------------------------------------------------------------//
    // 1. Método donde la computadora selecciona de forma aleatoria una opción   //
    //     [Piedra = 0] ~ [Papel = 1] ~ [Tijera = 2]                              //
    //----------------------------------------------------------------------------//
    public void cpuEleccion(){
        CPU_manoEleccion = random.nextInt(3);
        
        switch(CPU_manoEleccion){
            case 0:
                CPU_Roll.setIcon(new ImageIcon(getClass().getResource("Imagenes/CPU_Piedra.png")));
                break;
            case 1:
                CPU_Roll.setIcon(new ImageIcon(getClass().getResource("Imagenes/CPU_Papel.png")));
                break;
            case 2:
                CPU_Roll.setIcon(new ImageIcon(getClass().getResource("Imagenes/CPU_Tijeras.png")));
                break;
        }
    }
    
    //----------------------------------------------------------------------------//
    // 2. Método que reinicia los botones para volver a jugar.                   //
    //----------------------------------------------------------------------------//
    public void reiniciarBotones(){
        
        Boton_Piedra.setVisible(false);
        Boton_Papel.setVisible(false);
        Boton_Tijera.setVisible(false);
        
        Boton_Jugar.setVisible(true);
    }

    //----------------------------------------------------------------------------//
    // 3. Método que realiza el conteo de las partidas ganadas por el jugador.    //
    //----------------------------------------------------------------------------// 
    public void puntajeContadorAum(){
        contadorPuntaje++;
        Jugador_Puntaje.setText(String.valueOf(contadorPuntaje));       
    }
    
    //----------------------------------------------------------------------------//
    // 3. Método que realiza el conteo de las partidas perdidas por el jugador.    //
    //----------------------------------------------------------------------------// 
    public void puntajeContadorDism(){
        contadorPuntaje--;
        Jugador_Puntaje.setText(String.valueOf(contadorPuntaje));       
    }
    
    //----------------------------------------------------------------------------//
    // 4. Método que muestra la animación(.gif) de explosion de fondo.           //
    //     Cuando el contador de tiempo es igual a 2 seg la imagen es cambiada.   //
    //----------------------------------------------------------------------------//  
    public void explosionAnimacion(){
        temporizador = new Timer();
        
        Explosion.setIcon(new ImageIcon(getClass().getResource("Imagenes/Explosion(1).gif")));
        Explosion.setVisible(true);
        
        usoTemporizador = new TimerTask() {
            @Override
            public void run() {
                if(contadorTiempo == 2){
                    cancel();
                    Explosion.setIcon(new ImageIcon(getClass().getResource("Imagenes/Explosion(2).gif")));
                }
                contadorTiempo++;
            }
        };
        temporizador.schedule(usoTemporizador, 0, 1000);
        contadorTiempo = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Jugar = new javax.swing.JButton();
        Boton_Piedra = new javax.swing.JButton();
        Boton_Papel = new javax.swing.JButton();
        Boton_Tijera = new javax.swing.JButton();
        JugadorRoll = new javax.swing.JLabel();
        CPU_Roll = new javax.swing.JLabel();
        Estado_Tag = new javax.swing.JLabel();
        Titulo_Puntaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jugador_Puntaje = new javax.swing.JLabel();
        Boton_Reset = new javax.swing.JButton();
        Explosion = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Piedra Papel Tijera");
        setResizable(false);
        getContentPane().setLayout(null);

        Boton_Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_JugarDefecto.png"))); // NOI18N
        Boton_Jugar.setBorderPainted(false);
        Boton_Jugar.setContentAreaFilled(false);
        Boton_Jugar.setPreferredSize(new java.awt.Dimension(370, 110));
        Boton_Jugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_JugarPresionado.png"))); // NOI18N
        Boton_Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Jugar);
        Boton_Jugar.setBounds(270, 600, 370, 110);

        Boton_Piedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_PiedraDefecto.png"))); // NOI18N
        Boton_Piedra.setBorderPainted(false);
        Boton_Piedra.setContentAreaFilled(false);
        Boton_Piedra.setPreferredSize(new java.awt.Dimension(260, 160));
        Boton_Piedra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_PiedraPresionado.png"))); // NOI18N
        Boton_Piedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PiedraActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Piedra);
        Boton_Piedra.setBounds(30, 570, 260, 170);

        Boton_Papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_PapelDefecto.png"))); // NOI18N
        Boton_Papel.setBorderPainted(false);
        Boton_Papel.setContentAreaFilled(false);
        Boton_Papel.setPreferredSize(new java.awt.Dimension(262, 160));
        Boton_Papel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_PapelPresionado.png"))); // NOI18N
        Boton_Papel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PapelActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Papel);
        Boton_Papel.setBounds(330, 570, 262, 170);

        Boton_Tijera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_TijerasDefecto.png"))); // NOI18N
        Boton_Tijera.setBorderPainted(false);
        Boton_Tijera.setContentAreaFilled(false);
        Boton_Tijera.setPreferredSize(new java.awt.Dimension(260, 160));
        Boton_Tijera.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton_TijerasPresionado.png"))); // NOI18N
        Boton_Tijera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_TijeraActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Tijera);
        Boton_Tijera.setBounds(620, 570, 260, 170);

        JugadorRoll.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        JugadorRoll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Jugador_Roll.png"))); // NOI18N
        getContentPane().add(JugadorRoll);
        JugadorRoll.setBounds(210, 270, 280, 200);

        CPU_Roll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPU_Roll.png"))); // NOI18N
        getContentPane().add(CPU_Roll);
        CPU_Roll.setBounds(420, 160, 280, 200);

        Estado_Tag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listo_Tag.png"))); // NOI18N
        Estado_Tag.setPreferredSize(new java.awt.Dimension(600, 110));
        getContentPane().add(Estado_Tag);
        Estado_Tag.setBounds(150, 40, 600, 110);

        Titulo_Puntaje.setFont(new java.awt.Font("Txt_IV50", 1, 38)); // NOI18N
        Titulo_Puntaje.setForeground(new java.awt.Color(255, 0, 51));
        Titulo_Puntaje.setText("Puntaje: ");
        getContentPane().add(Titulo_Puntaje);
        Titulo_Puntaje.setBounds(10, 490, 270, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 500, 0, 0);

        Jugador_Puntaje.setFont(new java.awt.Font("Txt_IV50", 1, 30)); // NOI18N
        Jugador_Puntaje.setForeground(new java.awt.Color(255, 255, 255));
        Jugador_Puntaje.setText("123456");
        getContentPane().add(Jugador_Puntaje);
        Jugador_Puntaje.setBounds(250, 495, 130, 32);

        Boton_Reset.setBackground(new java.awt.Color(0, 0, 0));
        Boton_Reset.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        Boton_Reset.setForeground(new java.awt.Color(204, 204, 204));
        Boton_Reset.setText("Reiniciar");
        Boton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Reset);
        Boton_Reset.setBounds(810, 500, 90, 31);

        Explosion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Explosion.setPreferredSize(new java.awt.Dimension(430, 320));
        getContentPane().add(Explosion);
        Explosion.setBounds(150, 40, 600, 470);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 910, 780);

        setSize(new java.awt.Dimension(926, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //----------------------------------------------------------------------------//
    // > [Botón Jugar]                                                             //
    //----------------------------------------------------------------------------// 
    private void Boton_JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_JugarActionPerformed
        Boton_Jugar.setVisible(false);

        Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Listo_Tag.png")));
        Estado_Tag.setVisible(true);

        JugadorRoll.setIcon(new ImageIcon(getClass().getResource("Imagenes/Jugador_ManoRoll.gif")));
        CPU_Roll.setIcon(new ImageIcon(getClass().getResource("Imagenes/CPU_ManoRoll.gif")));
        JugadorRoll.setVisible(true);
        CPU_Roll.setVisible(true);

        Boton_Piedra.setVisible(true);
        Boton_Papel.setVisible(true);
        Boton_Tijera.setVisible(true);
    }//GEN-LAST:event_Boton_JugarActionPerformed

    //----------------------------------------------------------------------------//
    // > [Botón Piedra]                                                           //
    //----------------------------------------------------------------------------//  
    private void Boton_PiedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PiedraActionPerformed
        JugadorRoll.setIcon(new ImageIcon(getClass().getResource("Imagenes/Jugador_Piedra.png")));
        JugadorRoll.setVisible(true);
        cpuEleccion();
        explosionAnimacion();
        
        switch(CPU_manoEleccion){
            case 0:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Empate_Tag.png")));
                reiniciarBotones();
                break;
            case 1:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Perdiste_Tag.png")));
                puntajeContadorDism();
                reiniciarBotones();
                break;
            case 2:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Ganaste_Tag.png")));
                puntajeContadorAum();
                reiniciarBotones();
                break;
        }
    }//GEN-LAST:event_Boton_PiedraActionPerformed

    //----------------------------------------------------------------------------//
    // > [Botón Papel]                                                            //
    //----------------------------------------------------------------------------//   
    private void Boton_PapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PapelActionPerformed
        JugadorRoll.setIcon(new ImageIcon(getClass().getResource("Imagenes/Jugador_Papel.png")));
        JugadorRoll.setVisible(true);
        cpuEleccion();
        explosionAnimacion();
        
        switch(CPU_manoEleccion){
            case 0:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Ganaste_Tag.png")));
                puntajeContadorAum();
                reiniciarBotones();
                break;
            case 1:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Empate_Tag.png")));
                reiniciarBotones();
                break;
            case 2:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Perdiste_Tag.png")));
                puntajeContadorDism();
                reiniciarBotones();
                break;
        } 
    }//GEN-LAST:event_Boton_PapelActionPerformed

    //----------------------------------------------------------------------------//
    // > [Botón Tijera]                                                           //
    //----------------------------------------------------------------------------// 
    private void Boton_TijeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_TijeraActionPerformed
        JugadorRoll.setIcon(new ImageIcon(getClass().getResource("Imagenes/Jugador_Tijeras.png")));
        JugadorRoll.setVisible(true);
        cpuEleccion();
        explosionAnimacion();
        
        switch(CPU_manoEleccion){
            case 0:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Perdiste_Tag.png")));
                puntajeContadorDism();
                reiniciarBotones();
                break;
            case 1:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Ganaste_Tag.png")));
                puntajeContadorAum();
                reiniciarBotones();
                break;
            case 2:
                Estado_Tag.setIcon(new ImageIcon(getClass().getResource("Imagenes/Empate_Tag.png")));               
                reiniciarBotones();
                break;
        }         
    }//GEN-LAST:event_Boton_TijeraActionPerformed

    //----------------------------------------------------------------------------//
    // > [Botón Reiniciar]                                                        //
    //----------------------------------------------------------------------------//
    private void Boton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ResetActionPerformed
        Jugador_Puntaje.setText("0");
        contadorPuntaje = 0;

        Estado_Tag.setVisible(false);
        Explosion.setVisible(false);
        JugadorRoll.setVisible(false);
        CPU_Roll.setVisible(false);

        reiniciarBotones();
    }//GEN-LAST:event_Boton_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Jugar;
    private javax.swing.JButton Boton_Papel;
    private javax.swing.JButton Boton_Piedra;
    private javax.swing.JButton Boton_Reset;
    private javax.swing.JButton Boton_Tijera;
    private javax.swing.JLabel CPU_Roll;
    private javax.swing.JLabel Estado_Tag;
    private javax.swing.JLabel Explosion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel JugadorRoll;
    private javax.swing.JLabel Jugador_Puntaje;
    private javax.swing.JLabel Titulo_Puntaje;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
